FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .

EXPOSE 3000
EXPOSE 9229

CMD ["npx", "nodemon", "-L", "--exec", "node --inspect=0.0.0.0:9229", "main.js", "--", "--host", "0.0.0.0", "--port", "3000", "--cache", "./cache"]